os: linux
dist: jammy
if: fork = false

stages:
  - tests

jobs:
  include:
    - stage: tests
      name: Tests
      language: python
      python:
        - "3.9"
      services:
        - docker
      before_install: 
        - docker build -t queueprocessingfunction --build-arg ARCH="x86_64" --build-arg ENABLE_LAMBDA_INSIGHTS="false" --build-arg ENV="DEV"
      env:
        - PYTHONPATH="/var/task/src:/var/runtime"
        - AWS_SAM_LOCAL="True"
        - DEPLOYMENT_NAME="test"
        - POWERTOOLS_METRICS_NAMESPACE="local"
        - DYNATRACE_1_ENV_URL="https://abc1234.live.dynatrace.com"
        - DYNATRACE_1_API_KEY_PARAM="/dynatrace/s3-log-forwarder/dynatrace-s3-log-forwarder/tenant/api-key"
        - AWS_DEFAULT_REGION="us-east-1"
        - LOG_FORWARDER_CONFIGURATION_LOCATION="local"
      script:
        - docker run --entrypoint="" --mount type=bind,source="$TRAVIS_BUILD_DIR"/src,target=/var/task/tests queueprocessingfunction python -m unittest discover -s tests

