# Copyright 2023 Dynatrace LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#      https://www.apache.org/licenses/LICENSE-2.0

#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

eks:
  log_group_name:
    aws.resource.id:
      operation: split
      parameters:
        delimiter: "/"
        attribute_index: 3
  log_stream_name:
    log.source: 
      operation: find_strings
      parameters:
        strings:
          - kube-apiserver-audit
          - kube-apiserver
          - authenticator
          - kube-controller-manager
          - kube-scheduler
          - cloud-controller-manager
lambda:
  log_group_name:
    aws.resource.id: 
      operation: split
      parameters:
        delimiter: "/"
        attribute_index: 3
  log_stream_name: {}

route53: 
  # CloudWatch Log Group is user defined. For the forwarder to pick it up must be 
  # /aws/route53/...
  log_group_name: {}
  log_stream_name:
    aws.resource.id: 
      operation: split
      parameters:
        delimiter: "/"
        attribute_index: 0
    aws.edge_location: 
      operation: split
      parameters:
        delimiter: "/"
        attribute_index: 1